### ISSUE TITLE
Traceback messages on scan of some legacy images

### ISSUE THREAD

**Issue by shasheene** [rescuezilla/rescuezilla#127]
As mentioned in #126, Rescuezilla v2.0 introduced a user-interface element which displays the images present in the backup folder:

<a href="https://user-images.githubusercontent.com/1414379/96356380-f0272180-1134-11eb-8024-35a88b8d6429.png"><img src="https://user-images.githubusercontent.com/1414379/96356380-f0272180-1134-11eb-8024-35a88b8d6429.png" width="800"/></a>

A user has reported using Rescuezilla v2.0 produces traceback messages for _some_ of their legacy Rescuezilla v1.0.5 / Redo Backup v1.0.4 images:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rescuezilla/image_folder_query.py", line 93, in _populate_image_list_table
    image.get_enduser_friendly_partition_description()
  File "/usr/lib/python3/dist-packages/rescuezilla/parser/redobackup_legacy_image.py", line 203, in get_enduser_friendly_partition_description
    flat_string += "(" + str(partition_number) + ": " + self.flatten_partition_string(short_device_node) + ") "
  File "/usr/lib/python3/dist-packages/rescuezilla/parser/redobackup_legacy_image.py", line 231, in flatten_partition_string
    raise Exception(self.absolute_path + ": Unable to use " + str(partition_number) + " from " + short_device_node + " in " + str(self.sfdisk_dict) + " or " + str(self.partclone_info_dict))
Exception: /mnt/backup/[redacted]: Unable to use 10 from sda10 in {'partitions': OrderedDict([('/dev/sda1', {'start': 1, 'size': [redacted]}), ('/dev/sda2', {'start': 0, 'size': 0}), ('/dev/sda3', {'start': 0, 'size': 0}), ('/dev/sda4', {'start': 0, 'size': 0})]), 'unit': 'sectors'} or OrderedDict([(1, OrderedDict([('filesystem', 'EXTFS'), 
```

```
MACHINE NAME/REDACTED.backup: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rescuezilla/image_folder_query.py", line 133, in scan_file
    image = RedoBackupLegacyImage(absolute_path, enduser_filename, filename)
  File "/usr/lib/python3/dist-packages/rescuezilla/parser/redobackup_legacy_image.py", line 155, in __init__
    raise Exception("Unable to match any partclone images associated with " + short_device_node + ": " + image_match_string)
Exception: Unable to match any partclone images associated with sda5: /mnt/backup/LAPTOP NAME/REDACTED_part5.*
```

```
REDACTED.backup: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rescuezilla/image_folder_query.py", line 133, in scan_file
    image = RedoBackupLegacyImage(absolute_path, enduser_filename, filename)
  File "/usr/lib/python3/dist-packages/rescuezilla/parser/redobackup_legacy_image.py", line 155, in __init__
    raise Exception("Unable to match any partclone images associated with " + short_device_node + ": " + image_match_string)
Exception: Unable to match any partclone images associated with sda3: /mnt/backup/REDACTED_part3.*
```

The root cause is Rescuezilla v2.0 is assumes certain things exist related to the legacy Rescuezilla v1.0.5 / Redo Backup v1.0.4 images, and not all backups are meeting those assumptions, leading to the traceback messages shown above (which will be intimidating for many users).

For users needing to restore such legacy Rescuezilla v1.0.5 / Redo Backup v1.0.4 format images, the temporary workaround is to use Rescuezilla v1.0.6.1 which doesn't have the new image scanning feature added in Rescuezilla v2.0.

This issue will of course be resolved in the next version. Sorry for any inconvenience for anybody experiencing such teething issues with Rescuezilla v2.0's new automatic image scanning feature.

**Comment by shasheene** [comment]
Fixed in [Rescuezilla v2.1](https://github.com/rescuezilla/rescuezilla/releases/latest).
