### ISSUE TITLE
Clonezilla's "dev-fs.list" change (Oct 2020) causes Rescuezilla v2.0 scanning errors

### ISSUE THREAD

**Issue by shasheene** [rescuezilla/rescuezilla#139]
This issue only affects users of Clonezilla's bleeding edge "testing" ISO images since October 2020 using Rescuezilla v2.0.

Since October 9 2020, Clonezilla has [changed](https://gitlab.com/stevenshiau/clonezilla/-/commit/73eac32b38f13fd6fbce3ac724c06a6efb981207#218f341899d40dd2eee0257e3a7bf9507181f281_1682_1693) the data in the dev-fs.list file to save the file size information (`scripts/sbin/ocs-functions` line 1664). The dev-fs.list file now reads:

```
# <Device name>   <File system>   <Size>
# File system is got from ocs-get-part-info. It might be different from that of blkid or parted.
/dev/sda1 vfat 512M
/dev/sda2 ext4 976.6G
/dev/sda4 MS_Reserved_Partition 16M
/dev/sda5 ntfs 870G
/dev/sda3 swap 15.9G
```

Where as before it read:

```
# <Device name>   <File system>
# File system is got from ocs-get-part-info. It might be different from that of blkid or parted.
/dev/sda1 vfat
/dev/sda2 ext4
/dev/sda4 MS_Reserved_Partition
/dev/sda5 ntfs
/dev/sda3 swap
```

This minor difference causes the Rescuezilla scanning operation to be unable to process the image file:

```
Error processing the following images:

2020-11-21-15-img-uncompressed/parts: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rescuezilla/image_folder_query.py", line 127, in scan_file
    image = ClonezillaImage(absolute_path, enduser_filename)
  File "/usr/lib/python3/dist-packages/rescuezilla/parser/clonezilla_image.py", line 161, in __init__
    Utility.read_file_into_string(dev_fs_list_filepath))
  File "/usr/lib/python3/dist-packages/rescuezilla/parser/clonezilla_image.py", line 505, in parse_dev_fs_list_output
    long_dev_node, fs = line.split(" ")
ValueError: too many values to unpack (expected 2)
```

**Rescuezilla will be able to process this new dev-fs.list format in Rescuezilla v2.1.**

To ensure Rescuezilla v2.0 continues to be able to restore images created by more recent versions, Rescuezilla 2.1 will **not** write the size information into this file.

See also: Task #127 for "Traceback messages on scan of some legacy images"

**Comment by shasheene** [comment]
Fixed in [Rescuezilla v2.1](https://github.com/rescuezilla/rescuezilla/releases/latest).
