### ISSUE TITLE
Python error before chosing for destination

### ISSUE THREAD

**Issue by gabrieletassoni** [rescuezilla/rescuezilla#282]
Hi, when I try to start a clone from a disk (hdd) to another disk (ssd), both gpt and both of the same size, the gui just shows this error and I cannot advance to the next step:

![Istantanea_2021-11-09_17-30-56](https://user-images.githubusercontent.com/11076471/140965074-7a5a73d8-5fd6-44d4-999b-474b22f4b9af.png)

Here is the copy/paste of the message: 

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rescuezilla/handler.py", line 571, in next_tab
    self.source_drive_metadata_only_image = MetadataOnlyImage(self.clone_source_drive_key)
  File "/usr/lib/python3/dist-packages/rescuezilla/parser/metadata_only_image.py", line 138, in __init__
    drive_state_partitions_dict = self.drive_state[self.long_device_node]['partitions']
KeyError: 'partitions'
```

Thank you for any help.

**Comment by shasheene** [comment]
Hi @gabrieletassoni,

Thank you for the report. I haven't been able to reproduce this issue just now, at least based on what I thought could have been happening.

The log file would be invaluable in debugging this issue. Could you please launch the Rescuezilla environment, close the Rescuezilla window, open a Terminal and run the following command:

```
/usr/sbin/rescuezilla > /home/ubuntu/Desktop/logfile.txt
```

This will create a logfile on the desktop. Please send me it (either upload it here, or email rescuezilla at gmail).

Thanks again for the report!

**Comment by cRoCx** [comment]
I have ran into the same issue just now. Following scenario:

1. Cloned internal 1 TB SSD to external 2 TB HDD --> Upgraded/Replaced internal 1 TB SSD with an internal 2 TB SSD --> Cloned external 2 TB HDD to internal 2 TB SSD --> Enlarged Windows partition on upgraded internal SSD from ~1 TB to ~2 TB --> All working, no problems, perfect Windows migration
2. Cloned internal 2 TB SSD to external 2 TB HDD --> No errors --> Tried booting --> BSOD
3. Messed around with hardware encryption (Samsung Magician, Bitlocker) for the internal 2 TB SSD --> Found out that it is only supposed to work with a "Secure Erase" via Samsung Magician --> Found a bug (Secure Erase not working) --> Manually deleted all partitions, reinstalled Windows --> tried again to enable hardware encryption on internal 2 TB SSD --> No success, no encryption yet
5. Tried cloning external 2 TB SSD back to internal 2 TB SSD to see if it would get the original Windows back working --> Now I got the same error message as @gabrieletassoni got. --> @shasheene: Here's the [logfile.txt](https://github.com/rescuezilla/rescuezilla/files/8943657/logfile.txt)

**Comment by RE-Specto** [comment]
had the same issue but while choosing source disk, selected an sd-card (gpt, 12 partitions, macbook's internal card reader) and clicking next produced the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rescuezilla/handler.py", line 601, in next_tab
    self.source_drive_metadata_only_image = MetadataOnlyImage(self.clone_source_drive_key)
  File "/usr/lib/python3/dist-packages/rescuezilla/parser/metadata_only_image.py", line 138, in __init__
    drive_state_partitions_dict = self.drive_state[self.long_device_node]['partitions']
KeyError: 'partitions'

```

**Comment by shasheene** [comment]
I will get this fixed for the next release
