### ISSUE TITLE
"Clone stuck at 0%" on Rescuezilla v2.3.0

### ISSUE THREAD

**Issue by shasheene** [rescuezilla/rescuezilla#297]
Rescuezilla v2.3 [broke](https://sourceforge.net/p/rescuezilla/discussion/support/thread/6c0bd9e128/?limit=250#06a9) the ability to clone disks: an error occurs internally (due to a typo) but it happens silently and the user isn't even informed.

It's a simple fix (mistyped a variable name), but wasn't caught due to my time constraints during Rescuezilla v2.3 testing window.

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rescuezilla/handler.py", line 951, in _clone_confirmation_callback
    is_rescue=self.is_rescue,
AttributeError: 'Handler' object has no attribute 'is_rescue'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_python3_dist-packages_rescuezilla_rescuezilla.py.0.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rescuezilla/handler.py", line 951, in _clone_confirmation_callback
    is_rescue=self.is_rescue,
AttributeError: 'Handler' object has no attribute 'is_rescue'
```

**Comment by shasheene** [comment]
**[Fixed in Rescuezilla v2.3.1](https://github.com/rescuezilla/rescuezilla/releases/latest)**
