### ISSUE TITLE
Verify function on Rescuezilla v2.4 German language produced Python stack trace

### ISSUE THREAD

**Issue by shasheene** [rescuezilla/rescuezilla#352]
Found a comment where the user was evaluating the tool and had a bad experience:

> I created an USB thumbdrive using balenaEtcher. For testing Rescuezilla I used my Acer Aspire3 notebook, which runs quite well under Linux, e.g. with Ubuntu and Slackware.
> I wanted to create an image of an ext4 partition and save that image on my USB HDD. Since the rescuezilla program starts automatically after booting, it should be possible to use that USB drive for storing the image when this drive is plugged in while the rescuezilla app is already running, but it does not get recognized. Thus I had to quit the app and restart it manually.
> I created the image using zstd compression. After that I tested the verify function, but that ended reproducible in a quite strange error message printing a python backtrace.
> I wanted to google that error message, but it was impossible to access the internet via WIFI due to an issue with DBUS and wpa_supplicant. After that I gave up testing Rescuezilla ...

Interesting that the user was unable to verify a ZSTD compressed image created using Rescuezilla.

Displaying an error message with a Python stacktrace is a last resort. (TODO: Create ticket for "submit error report" button)

Sounds like he chose to make an image of a single EXT4 partition. I'll double check the logic of verifying Clonezilla images of this situation. It should work, I'm surprised it didn't.

Separate TODO: Try and reproduce the reported wifi issue

**Comment by shasheene** [comment]
An anonymous posted a photo [reports](https://sourceforge.net/p/rescuezilla/discussion/support/thread/6aea970e01/?limit=25#29e5)
![IMG_2307](https://user-images.githubusercontent.com/1414379/184169667-1a43f426-a564-49b9-aab7-1498856fdec0.png). Here's a transcription for search engines:

```
Error verifying image: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rescuezilla/verify_manager.py", line 100, in
do_verify_wrapper
    self.do_verify()
  File "/usr/lib/python3/dist-packages/rescuezilla/verify_manager.py", line 329, in
do_verify
    self.summary_message += _("✔") + _("{partition}: filesystem image successfully verified.").format(partition=partition_key) + "\n
KeyError: 'Partition'
```

This will be fixed in Rescuezilla v2.4.1 this weekend.

**Comment by shasheene** [comment]
Ah this only occurs in German language, because the translation string's substitution variable contains a capital letter:
```
src/apps/rescuezilla/rescuezilla/usr/share/locale/de/LC_MESSAGES/rescuezilla.po:msgstr "{Partition}: Dateisystemabbild erfolgreich verifiziert."
```

It's a trivial fix in this case. The broader fix is having Weblate and Rescuezilla's build scripts automatically detect this situation and provide a loud error so it can be fixed before release.

**Comment by shasheene** [comment]
Keeping this issue open until v2.4.1 actually released. Side note: found similar issues in French, Danish and Catalan translations too. Fixing for v2.4.1.
