### ISSUE TITLE
Integrate Sentry.IO Error Reporting

### ISSUE THREAD

**Issue by shasheene** [rescuezilla/rescuezilla#371]
[Sentry.IO](https://sentry.io/) provides a free web-interface and SDK to detect when Python exceptions happen.

The official Ubuntu repository has the `python3-sentry-sdk` package already present.

The error reports will help avoid quickly learn about issues like [#352](https://github.com/rescuezilla/rescuezilla/issues/352).

I need to write a privacy document as per #340

**Comment by CryptGoat** [comment]
I understand the desire for more data to get a quick grip to identify and fix problems of Rescuezilla but I feel strongly negative about automated error reporting. Many Linux distributions and also Rescuezilla are highly regarded and widely used by users who value their privacy. Pretty much no Linux distribution does send data about the system by default and if they did at some point it always backfired big in their respective community. Not even Apport in Ubuntu does send crash reports by itself. Also, Sentry is third party US based company. Not sure if I want them to handle my system data (yes, I know Sentry is widely used and I'm writing this on MS owned GitHub right now).

Distribute Rescuezilla for Backup purposes on USB flash drives at privacy events and there's no way I include this if it sends data about the user's device by default. If you still decide to include error reporting please make it at-least **entirely** opt-in and make that choice and the info sent as transparent as possible.

**Comment by shasheene** [comment]
Yep, good argument for not including it in v2.4.1.

And also good argument against enabled by default in Rescuezilla.

What about a checkbox on the initial "Welcome" page of Rescuezilla that reads something like "Automatically upload error details"? It could be left unticked by default. Then users having trouble would have to decide to go back and tick the box and reproduce the error. Still an improvement on what I currently have.

Another approach is a button or checkbox on the error message box that uploads the details. That would work, but it won't catch the places that don't currently generate an error box.

**Comment by shasheene** [comment]
Similar issue reported by [a user on the Rescuezilla support forum](https://sourceforge.net/p/rescuezilla/discussion/support/thread/1c90af6db8/?limit=25)

```
"Error creating backup: Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/rescuezilla/backup_manager.py", line
131, in do_backup_wrapper
self.do_backup()
File "/usr/lib/python3/dist-packages/rescuezilla/backup_manager.py", line
245, in do_backup
process, flat_command_string, failed_message = Utility.run("Saving
Info-lshw.txt", ["lshw"], use_c_locale=True,
output_filepath=info_lshw_filepath, logger=self.logger)
File "/usr/lib/python3/dist-packages/rescuezilla/utility.py", line 502,
in run
process = subprocess.run(cmd_list, encoding='utf-8',
capture_output=True, env=env)
File "/usr/lib/python3.10/subprocess.py", line 503, in run
stdout, stderr = process.communicate(input, timeout=timeout)
File "/usr/lib/python3.10/subprocess.py", line 1152, in communicate
stdout, stderr = self._communicate(input, endtime, timeout)
File "/usr/lib/python3.10/subprocess.py", line 2041, in _communicate
stdout = self._translate_newlines(stdout,
File "/usr/lib/python3.10/subprocess.py", line 1029, in
_translate_newlines
data = data.decode(encoding, errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 40517:
invalid continuation byte"
```

I responded:

> Sorry to here about your experience here.
> 
> This is a bug in Rescuezilla. It's trying to run the command to list the hardwae on your system and save it to a file, purely for informational purposes (not used for the backup/restore). Clonezilla runs the same command to save the same file for the same reason.
> 
> But Rescuezilla is clearly failing here, because it can't process the output of the external program.
> 
> I had a similar error reported 2 weeks ago when a different Rescuezilla [tries to save some other information using a different command (#412)](https://github.com/rescuezilla/rescuezilla/issues/412).
> 
> Clearly there's a systemic issue with how Rescuezilla v2.4.2 and earlier are handling the external programs being used, as it's not able to process the output.
> 
> I have also heard of other users claiming to have seen a stacktrace/backtrace error message, but I don't have insight into what that error was (users appear [vehemently against including any kind of automated error reporting](https://github.com/rescuezilla/rescuezilla/issues/371#issuecomment-1231284528), so I need to build out a manual error reporting mechanism so I can receive these reports and fix them faster).
> 
> In my previous testing, I haven't seen this issue on my test environment. I will try and figure it out, because it obviously causes a terrible user experience for Rescuezilla.
> 
> [...]
>
> I will be taking several weeks off work to work on Rescuezilla starting in a few weeks time. There's a lot of features I want to develop, but clearly improving stability needs to be the first priority.
> 
> Apologies again for the terrible user-experience you've just had.

This systemic issue around processing output of the application appears to be the number 1 issue with Rescuezilla v2.4.2 and earlier I will fix it with highest priority.
