### ISSUE TITLE
Rescuezilla allows users to name backups with "[" and "]

### ISSUE THREAD

**Issue by shasheene** [rescuezilla/rescuezilla#375]
```
parts: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rescuezilla/image_folder_query.py", line 185, in scan_file
    temp_image_dict = ClonezillaImage.get_clonezilla_image_dict(absolute_path, enduser_filename)
  File "/usr/lib/python3/dist-packages/rescuezilla/parser/clonezilla_image.py", line 159, in get_clonezilla_image_dict
    clonezilla_image_dict[key] = ClonezillaImage(absolute_clonezilla_img_path, enduser_filename, dir,
  File "/usr/lib/python3/dist-packages/rescuezilla/parser/clonezilla_image.py", line 284, in __init__
    mbr_glob_list = glob.glob(os.path.join(dir, short_disk_device_node) + "-mbr")
  File "/usr/lib/python3.9/glob.py", line 22, in glob
    return list(iglob(pathname, recursive=recursive))
  File "/usr/lib/python3.9/glob.py", line 74, in _iglob
    for dirname in dirs:
  File "/usr/lib/python3.9/glob.py", line 74, in _iglob
    for dirname in dirs:
  File "/usr/lib/python3.9/glob.py", line 75, in _iglob
    for name in glob_in_dir(dirname, basename, dironly):
  File "/usr/lib/python3.9/glob.py", line 86, in _glob1
    return fnmatch.filter(names, pattern)
  File "/usr/lib/python3.9/fnmatch.py", line 58, in filter
    match = _compile_pattern(pat)
  File "/usr/lib/python3.9/fnmatch.py", line 52, in _compile_pattern
    return re.compile(res).match
  File "/usr/lib/python3.9/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.9/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.9/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.9/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.9/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.9/sre_parse.py", line 834, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "/usr/lib/python3.9/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.9/sre_parse.py", line 598, in _parse
    raise source.error(msg, len(this) + 1 + len(that))
re.error: bad character range 9-0 at position 27
```

**Comment by shasheene** [comment]
Huh, weird duplication. Meant #376
