### ISSUE TITLE
Rescuezilla last version cancel to start backup

### ISSUE THREAD

**Issue by slocane** [rescuezilla/rescuezilla#402]
Backup operation failed:

Error creating backup: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rescuezilla/backup_manager.py", line 131, in do_backup_wrapper
    self.do_backup()
  File "/usr/lib/python3/dist-packages/rescuezilla/backup_manager.py", line 413, in do_backup
    process, flat_command_string, failed_message = Utility.run("Saving EFI NVRAM info",
  File "/usr/lib/python3/dist-packages/rescuezilla/utility.py", line 502, in run
    process = subprocess.run(cmd_list, encoding='utf-8', capture_output=True, env=env)
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1149, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.10/subprocess.py", line 2038, in _communicate
    stdout = self._translate_newlines(stdout,
  File "/usr/lib/python3.10/subprocess.py", line 1026, in _translate_newlines
    data = data.decode(encoding, errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 106: invalid start byte

**Comment by shasheene** [comment]
Ahh duplicate error to #412

Exact same command too. Highest priority bug current in Rescuezilla, will figure out the root cause and fix for next release.
