### ISSUE TITLE
Clone operation failed with Rescuezilla-2.4.2-64bit.jammy. But clonezilla 3.0.3-22-did the same job without errors

### ISSUE THREAD

**Issue by Gitfredenpunkt** [rescuezilla/rescuezilla#412]
The job: Clone the partitions Win11, NeptuneOS and Mint Mate from SSD-512GB ---> SSD-1TB

Error restoring image: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rescuezilla/clone_manager.py", line 111, in do_clone_wrapper
    self.do_clone()
  File "/usr/lib/python3/dist-packages/rescuezilla/clone_manager.py", line 146, in do_clone
    is_success, message = self.backup_manager.start_backup(selected_drive_key=self.image.long_device_node,
  File "/usr/lib/python3/dist-packages/rescuezilla/backup_manager.py", line 104, in start_backup
    return self.do_backup()
  File "/usr/lib/python3/dist-packages/rescuezilla/backup_manager.py", line 413, in do_backup
    process, flat_command_string, failed_message = Utility.run("Saving EFI NVRAM info",
  File "/usr/lib/python3/dist-packages/rescuezilla/utility.py", line 502, in run
    process = subprocess.run(cmd_list, encoding='utf-8', capture_output=True, env=env)
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1152, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.10/subprocess.py", line 2041, in _communicate
    stdout = self._translate_newlines(stdout,
  File "/usr/lib/python3.10/subprocess.py", line 1029, in _translate_newlines
    data = data.decode(encoding, errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa6 in position 109: invalid start byte

**Comment by shasheene** [comment]
Similar issue reported by [a user on the Rescuezilla support forum](https://sourceforge.net/p/rescuezilla/discussion/support/thread/1c90af6db8/?limit=25)

```
"Error creating backup: Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/rescuezilla/backup_manager.py", line
131, in do_backup_wrapper
self.do_backup()
File "/usr/lib/python3/dist-packages/rescuezilla/backup_manager.py", line
245, in do_backup
process, flat_command_string, failed_message = Utility.run("Saving
Info-lshw.txt", ["lshw"], use_c_locale=True,
output_filepath=info_lshw_filepath, logger=self.logger)
File "/usr/lib/python3/dist-packages/rescuezilla/utility.py", line 502,
in run
process = subprocess.run(cmd_list, encoding='utf-8',
capture_output=True, env=env)
File "/usr/lib/python3.10/subprocess.py", line 503, in run
stdout, stderr = process.communicate(input, timeout=timeout)
File "/usr/lib/python3.10/subprocess.py", line 1152, in communicate
stdout, stderr = self._communicate(input, endtime, timeout)
File "/usr/lib/python3.10/subprocess.py", line 2041, in _communicate
stdout = self._translate_newlines(stdout,
File "/usr/lib/python3.10/subprocess.py", line 1029, in
_translate_newlines
data = data.decode(encoding, errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 40517:
invalid continuation byte"
```

I responded:

> Sorry to here about your experience here.
> 
> This is a bug in Rescuezilla. It's trying to run the command to list the hardwae on your system and save it to a file, purely for informational purposes (not used for the backup/restore). Clonezilla runs the same command to save the same file for the same reason.
> 
> But Rescuezilla is clearly failing here, because it can't process the output of the external program.
> 
> I had a similar error reported 2 weeks ago when a different Rescuezilla [tries to save some other information using a different command (#412)](https://github.com/rescuezilla/rescuezilla/issues/412).
> 
> Clearly there's a systemic issue with how Rescuezilla v2.4.2 and earlier are handling the external programs being used, as it's not able to process the output.
> 
> I have also heard of other users claiming to have seen a stacktrace/backtrace error message, but I don't have insight into what that error was (users appear [vehemently against including any kind of automated error reporting](https://github.com/rescuezilla/rescuezilla/issues/371#issuecomment-1231284528), so I need to build out a manual error reporting mechanism so I can receive these reports and fix them faster).
> 
> In my previous testing, I haven't seen this issue on my test environment. I will try and figure it out, because it obviously causes a terrible user experience for Rescuezilla.
> 
> [...]
>
> I will be taking several weeks off work to work on Rescuezilla starting in a few weeks time. There's a lot of features I want to develop, but clearly improving stability needs to be the first priority.
> 
> Apologies again for the terrible user-experience you've just had.

This systemic issue around processing output of the application appears to be the number 1 issue with Rescuezilla v2.4.2 and earlier I will fix it with highest priority.

**Comment by lamosca01** [comment]
The same thing happens to me on a pc that has a 2TB nvme disk. I was using a 2TB hard drive and I thought that was the fault, but I tried a bigger one and it returned the same error.

**Comment by shasheene** [comment]
Oh I missed that I never got around to fixing this. Another user has reported the same error: https://sourceforge.net/p/rescuezilla/discussion/support/thread/2bb8cee47a/?limit=25#7e3d

I wrote:

> Sorry, this is a bug on Rescuezilla's backup logic that been around for quite along time. There's an old GitHub issue here: https://github.com/rescuezilla/rescuezilla/issues/412 I intended to fix it earlier but never got around to it
> 
> I'm in the final stages of testing the upcoming Rescuezilla 2.6.1 (to be released in next day or two I think), and I don't want to risk introducing new changes to it so I can get that release (which contains a lot of other improvements) out to users faster.
> 
> I will look to make the change in the subsequent Rescuezilla release (v2.7)
> 
> The issue is the tool that reads your EFI system variables is generating some unexpected data, so it's likely this issue with creating the backup will persistently impact the specific hardware here.

**Comment by motrengaw** [comment]
Same issue on a Dell Optiplex, resolved by editing utility.py, adding errors='replace' flag to the subprocess.run() arguments in a root terminal on v2.6.2-64

process = subprocess.run(cmd_list, encoding='utf-8', errors='replace', capture_output=True, env=env)
