### ISSUE TITLE
Error in Portuguese translation of Rescuezilla v2.4.2 breaks cloning

### ISSUE THREAD

**Issue by shasheene** [rescuezilla/rescuezilla#438]
A user writes:

> Error when clone disk.. help ;(
>
> Falha ao restauarar imagem: Traceback (most recent call last):
> File "/usr/lib/python3/dist-packages/rescuezilla/clone_manager.py", line 111, in do_clone_wrapper
> self.do_clone()
> File "/usr/lib/python3/dist-packages/rescuezilla/clone_manager.py", line 168, in do_clone
> is_success, message = self.restore_manager.start_restore(image=self.image,
> File "/usr/lib/python3/dist-packages/rescuezilla/restore_manager.py", line 102, in start_restore
> return self.do_restore()
> File "/usr/lib/python3/dist-packages/rescuezilla/restore_manager.py", line 1016, in do_restore
> growing_filesystem_message = _(
> KeyError: 'partição'

![Captura de tela_2023-08-01_02-29-27](https://github.com/rescuezilla/rescuezilla/assets/1414379/04c99387-ae84-49e0-80ce-0a1f08d6efab)

I responded:

> Oh, this is an error **in the Portuguese translation** introduced in Rescuezilla v2.4.2 (2023-03-05).
> 
> Please use a different language (eg, English) to avoid the bug until the next version of Rescuezilla.
> 
> In more detail, a user [translated](https://github.com/rescuezilla/rescuezilla/commit/ec3f9010dee8216c241eccc2ece5ccd3d83bfb98#diff-bf1785b619513610179148292d8131e84ee389239d2e91a5055d7785ab71f011R715) the cloning feature into Portuguese, where the word `{partition}` was accidentally translated into Portuguese despite Rescuezilla needing that word to be unmodified / in English for the program to work.
> 
> The line has *already* been [fixed](https://github.com/rescuezilla/rescuezilla/commit/ec3f9010dee8216c241eccc2ece5ccd3d83bfb98#diff-bf1785b619513610179148292d8131e84ee389239d2e91a5055d7785ab71f011L715) by another translator using the [Weblate tool](https://hosted.weblate.org/translate/rescuezilla/rescuezilla/pt/?q=Growing+filesystem&sort_by=-priority%2Cposition&checksum=#history) but I haven't yet released a new version of Rescuezilla that includes the fix.

**Comment by shasheene** [comment]
Fix to this GitHub issue available now as ["Weekly" Rolling Release (2023-11-26)](https://github.com/rescuezilla/rescuezilla/releases), which will largely form the upcoming Rescuezilla v2.5 release.
