### ISSUE TITLE
Error opening image file

### ISSUE THREAD

**Issue by Craigp23** [rescuezilla/rescuezilla#454]
I'd be grateful for any help with this error when attempting to open an image file with RescueZilla v2.3.1 64bit. TIA :)
 
MacBookPro-Mid2012-2023-08-20-1723-img-rescuezilla/parts: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rescuezilla/image_folder_query.py", line 185, in scan_file
    temp_image_dict = ClonezillaImage.get_clonezilla_image_dict(absolute_path, enduser_filename)
  File "/usr/lib/python3/dist-packages/rescuezilla/parser/clonezilla_image.py", line 159, in get_clonezilla_image_dict
    clonezilla_image_dict[key] = ClonezillaImage(absolute_clonezilla_img_path, enduser_filename, dir,
  File "/usr/lib/python3/dist-packages/rescuezilla/parser/clonezilla_image.py", line 255, in __init__
    Utility.read_file_into_string(parted_filepath))
  File "/usr/lib/python3/dist-packages/rescuezilla/utility.py", line 278, in read_file_into_string
    data = file.read()
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbd in position 2: invalid start byte

**Comment by Craigp23** [comment]
PS The image folder contains "46 items, totalling 71.6 GB"

**Comment by shasheene** [comment]
Sorry for your experience


This was [known](https://github.com/rescuezilla/rescuezilla/issues/412) [issue](https://github.com/rescuezilla/rescuezilla/pull/443) impacting a small number of systems. 

**The root cause was fixed [a few weeks ago (#402)](https://github.com/rescuezilla/rescuezilla/issues/402) but the upcoming version with the fix (Rescuezilla v2.5) has not yet been released.**

Rescuezilla v2.5 is only awaiting final testing. It will probably be released in less than 2 weeks, but since it seems you really need the release I will try and release it sooner

**Comment by Craigp23** [comment]
> Sorry for your experience
> 
> This was [known](https://github.com/rescuezilla/rescuezilla/issues/412) [issue](https://github.com/rescuezilla/rescuezilla/pull/443) impacting a small number of systems.
> 
> **The root cause was fixed [a few weeks ago (#402)](https://github.com/rescuezilla/rescuezilla/issues/402) but the upcoming version with the fix (Rescuezilla v2.5) has not yet been released.**
> 
> Rescuezilla v2.5 is only awaiting final testing. It will probably be released in less than 2 weeks, but since it seems you really need the release I will try and release it sooner

Good to hear, thanks for all your efforts! :) I'd be happy to try a beta if available?

**Comment by shasheene** [comment]
Hey @Craigp23,

**Could you please upload the file named something like `sda-pt.parted`**  (it may not have the `sda` in the name) so I can take a look? It's a small text file contains some non-sensitive information about your system. If you don't want to upload it here you can send it to rescuezilla at gmail.

It appears this instance of the bug is actually slightly different to the one I fixed a few months ago.

Your file will allow me to confirm I've fixed the bug before releasing Rescuezilla v2.5 in the next day or so.

Thanks!

**Comment by Craigp23** [comment]
Hey Shasheen :)

Does this help?

Thanks!

**Comment by shasheene** [comment]
@Craigp23

I might be missing something, but I can't see the attached file because it looks like you sent it to the GitHub reply email address and it appears that way of responding won't automatically shift email attachments to GitHub it seems.

Please reupload it on the GitHub website or email rescuezilla at gmail directly and I'll take a look!
